### ISSUE TITLE
Add assertion methods to handle arrays and collections

### ISSUE THREAD

**Issue by jlink** [junit-team/junit-framework#167]
It could be done with external assertion libraries but it's so common and it was part of JUnit 4.

Could be added to `Assertions` or could live in separate container(s), e.gl `CollectionAssertions` and `ArrayAssertions`.

**Comment by hotchemi** [comment]
Anyone working on it?

**Comment by marcphilipp** [comment]
No, feel free to start working on it. :smiley:

**Comment by hotchemi** [comment]
Gotcha :+1:

**Comment by hotchemi** [comment]
@jlink Before getting started, do you have any rough idea? I know assertj already provides fluent api but should we keep the api simple?

**Comment by sbrannen** [comment]
@hotchemi, let's aim for a simple solution along the lines of the simplicity of the existing assertion methods in `Assertions`. 

Keep in mind that we do not want to invest a lot of time (and maintenance down the road) in JUnit 5 regarding assertions, especially due to the rich feature sets provided by third-party libraries like AssertJ, Hamcrest, etc.

In other words, let's follow the _KISS_ principle and see how far that gets us.

Cheers!

**Comment by jlink** [comment]
I'd go for simple methods analogous to arrayEquals in JUnit 4.

**Comment by marcphilipp** [comment]
@hotchemi Are you still interested in working on this issue?

**Comment by hotchemi** [comment]
@marcphilipp Oh sorry! Just forgot so I'm gonna do this in this weekend.

**Comment by lutovich** [comment]
I can start working on this issue, if you do not mind @hotchemi.

@sbrannen my understanding is that users usually rely on collections to implement proper `equals()` method and than just use `assertEquals()` to check them. so there are no collection assertions in JUnit 4. do you think it makes sense to add only array assertions to JUnit 5 as well?

**Comment by hotchemi** [comment]
@lutovich Sorry, I've stopped this issue so please do that!

**Comment by sbrannen** [comment]
@lutovich,

You're right: JUnit 4 does not provide explicit assertions for collections.

If you have time, you could experiment with `assertEquals(Iterable, Iterable)`, `assertEquals(Iterable, Iterable, String)`, and `assertEquals(Iterable, Iterable, Supplier<String>)` variants, but that might turn out to be more effort than it's worth _to get it right_.

So, I would first focus on `assertArrayEquals(...)` variants and submit that work in a single pull request.

**Comment by lutovich** [comment]
@sbrannen I have couple questions related to this task. Sorry for the long post :)

In JUnit 4 methods `assertEquals(double, double)` and `assertEquals(float, float)` are deprecated and there are versions which accept an additional delta. Same applies to `assertArrayEquals(float[], float[])` and `assertArrayEquals(double[], double[])`.
In JUnit 5 number comparison is done simply with `!=` and there are no methods that take delta.

 1) should the comparison of doubles and floats use `Double.doubleToLongBits()` and `Float.floatToIntBits()` like `Arrays.equals()` does inside?
 2) should there be methods that accept delta?

It is possible to implement specialized and generic version for `assertArrayEquals()` in JUnit 5. Specialized version will have quite a bit of code duplication as `Arrays.equals()` does. Generic version will contain only one actual implementation and use `java.lang.reflect.Array`. Performance of the specialized version seem to be better. I've made a quick benchmark here: https://gist.github.com/lutovich/941d6f92813c2c34e660ba4fe687d330 it results in:

```
Benchmark    (elementsCount)   Mode  Cnt      Score      Error   Units
reflective                 1  thrpt   25   5674.135 ±   35.668  ops/ms
specialized                1  thrpt   25  60553.981 ± 1851.751  ops/ms

reflective                10  thrpt   25    620.776 ±   15.434  ops/ms
specialized               10  thrpt   25  29660.840 ± 1350.804  ops/ms

reflective               100  thrpt   25     63.113 ±    1.187  ops/ms
specialized              100  thrpt   25  11523.294 ±  585.673  ops/ms

reflective              1000  thrpt   25      6.364 ±    0.158  ops/ms
specialized             1000  thrpt   25   1865.229 ±  114.042  ops/ms

reflective            100000  thrpt   25      0.060 ±    0.003  ops/ms
specialized           100000  thrpt   25     17.315 ±    1.335  ops/ms
```

I was leaning towards reflection based approach before benchmarking. Now I'm not so sure because perf difference is quite significant.

 3) what is more preferable, performance or no code duplication?

Thanks!

**Comment by sbrannen** [comment]
Hi @lutovich,

Thanks for the detailed analysis!

> 1) should the comparison of doubles and floats use `Double.doubleToLongBits()` and `Float.floatToIntBits()` like `Arrays.equals()` does inside?

Yes, I think that's a good idea.

> 2) should there be methods that accept delta?

Yes. This omission was an unfortunate oversight on our part. We definitely need to accept a `delta` for comparing primitive doubles and floats.

> 3) what is more preferable, performance or no code duplication?

I'd go for performance in this case.

Cheers,

Sam

**Comment by sbrannen** [comment]
@lutovich,

Regarding adding support for deltas for floats and doubles, do you plan to address that in conjunction with your solution for this issue?

Or do you want us to create a new issue to address the lacking support for deltas?

**Comment by lutovich** [comment]
@sbrannen thanks for the answers! I can fix comparison for doubles/floats first in a separate PR and then proceed with array assertions.

**Comment by sbrannen** [comment]
Sounds good.

By the way, the `delta` support for existing assertion methods should be addressed in conjunction with #269.

**Comment by sbrannen** [comment]
This issue is currently slated for 5.0.0-M2; however, if it is completed in time it may be included in 5.0.0-M1.

**Comment by lutovich** [comment]
I'm still working on this task. Here is WIP: https://github.com/lutovich/junit5/commit/b95bf659a3bf98dcdceef75c8daf6bd9fe2c8be6.
Some tests are missing as well as methods for `float[]` and `double[]` that accept delta. I'll base PR on https://github.com/junit-team/junit5/pull/270 to reuse some methods from it.

**Comment by sbrannen** [comment]
Please base your PR on `master` now since #270 has already been merged.

**Comment by sbrannen** [comment]
The WIP is coming along nicely. Keep up the good work.

**Comment by sbrannen** [comment]
Hi @lutovich,

Do you think you'll find time to complete this in time for the 5.0 M1 release next week?

**Comment by lutovich** [comment]
@sbrannen I'll finish this weekend. sorry, it takes me really long time to complete this task.

**Comment by sbrannen** [comment]
@lutovich, no worries. If it makes it into M1, great! And if it doesn't get in until M2, that's also fine. 😉

**Comment by lutovich** [comment]
Hello @sbrannen,

I've submitted a PR about array assertions https://github.com/junit-team/junit5/pull/289. It does not fully close this issue. Support of assertions for iterables is still something to consider. Imo it is not worth adding them because iterables can already be checked using `assertEquals(Object, Object)`. Prettier checks can be done using additional libraries like Hamcrest or AssertJ.

Implementation of assertions for iterables seem doable and simpler than assertion for `Object[]`. It might get trickier if classes of given iterables are checked as well as their elements.

If assertions for iterables are considered than assertions for streams should probably be considered as well. Those two now seem like equal first class citizens in java.

I'll proceed with a prototype for `assertEquals(Iterable, Iterable)` to see how it can actually look like.

**Comment by sbrannen** [comment]
@lutovich, thanks for the PR!

We'll review it and hopefully merge it this week.

Note that M1 has been postponed until June 8th. So we still have adequate time.

**Comment by sbrannen** [comment]
Closing this issue since the core requirement (i.e., assertions for arrays) has been merged into `master

**Comment by jbduncan** [comment]
Hi @lutovich. Since I was inspired by this issue and I was a bit bored, I decided to create my own prototype for `assertIterableEquals`, and I think I've actually produced something that is worthwhile - however I only just realised in the last hour or so that you said you'd work on a prototype yourself. So I just want to ask how you'd feel if I were to submit a Pull Request for my own prototype?

**Comment by lutovich** [comment]
Hello @jbduncan, please feel free to submit a pull request. My prototype is only in my head now :)

**Comment by jbduncan** [comment]
Great!
It will probably take me a few days or so to submit a PR, as I'm rather new to contributing on GitHub and I'm busy with other things. So if you come up with your own prototype and I've not submitted a PR by then, you may take that as an invitation to submit your own. :)
