### ISSUE TITLE
Add assertion methods to handle iterators and streams

### ISSUE THREAD

**Issue by jbduncan** [junit-team/junit-framework#536]
With the merging of https://github.com/junit-team/junit5/pull/294 into master, I think it's a good time now to discuss whether deep equality assertion methods for iterators and streams, like `assert(Iterator|Stream)Equals`, should be introduced.

In my opinion, since `assertIterableEquals` exists now, it would be a silly oversight to not have support for the other two enumera(ble|tor) concepts as well.

I also think that a number of users would expect such assertion methods to exist, as `@TestFactory` methods currently support returning `Iterable`s, `Iterator`s and `Stream`s of `DynamicTest`s.

What does everyone think of this?

**Comment by jbduncan** [comment]
FYI I'd be happy to implement this if it's worthwhile and noone else has the time to do so.

**Comment by marcphilipp** [comment]
Personally, I think we should refrain from adding too many assertions. Both Iterators and Stream are easily converted into a Collection or Iterable in order to use the existing assertion methods.

@junit-team/junit-lambda What do you guys think?

**Comment by mlevison** [comment]
Simplicity is preferable. There should be one and only one option for each type. The more options - the more cognitive load, the more tiny mistakes. In addition we will be fuelling years of future debate over which one to use when :-)

Cheers
Mark

On October 31, 2016 at 11:01:58 AM, Marc Philipp (notifications@github.com) wrote:

Personally, I think we should refrain from adding too many assertions. Both Iterators and Stream are easily converted into a Collection or Iterable in order to use the existing assertion methods.

@junit-team/junit-lambda What do you guys think?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

-- 
Mark Levison
Sent with Airmail

**Comment by sbrannen** [comment]
> Personally, I think we should refrain from adding too many assertions. Both Iterators and Stream are easily converted into a Collection or Iterable in order to use the existing assertion methods.
> 
> @junit-team/junit-lambda What do you guys think?

I agree.

**Comment by marcphilipp** [comment]
@mlevison The assertions included in Jupiter are only meant as a starting point. You almost always want better assertions as provided by Hamcrest or AssertJ.

**Comment by jbduncan** [comment]
All the arguments given here against my proposal actually sound very reasonable to me! In light of those arguments, I'd be happy to this issue to be closed if no one has any objections. :)

**Comment by marcphilipp** [comment]
Alright, I'll close it for now.
